latitude_sgt = "0.5364391"
longitude_sgt = "117.5198197"
location_name = "Wisma Prima Camp, KPC, Sangatta"
sample_url = "http://localhost:8000/api/api-product"
auth_url = '{add auth url to authentication login}'
tbl_hp = "{add table related to this data}"
tbl_hs = "{add table related to this data}"
tbl_lp = "{add table related to this data}"
tbl_ls = "{add table related to this data}"
db_connection_string = "mysql+mysqlconnector://ryan:Samarinda123@localhost/flutter-pos-db"