latitude_sgt = "0.5364391"
longitude_sgt = "117.5198197"
location_name = "Wisma Prima Camp, KPC, Sangatta"
sample_url = "https://posflutter.ismail.id/api/api-product"
auth_url = "https://posflutter.ismail.id/api/login"
table_name = "products"
db_connection_string = "mysql+mysqlconnector://u311305858_testing:o~7F~o[ME@154.41.240.68/u311305858_testing"