latitude_sgt = "0.5364391"
longitude_sgt = "117.5198197"
location_name = "Wisma Prima Camp, KPC, Sangatta"
sample_url = "https://posflutter.ismail.id/api/api-product"
auth_url = "https://posflutter.ismail.id/api/login"
tbl_hp = "{add table related to this data}"
tbl_hs = "{add table related to this data}"
tbl_lp = "{add table related to this data}"
tbl_ls = "{add table related to this data}"
db_connection_string = "mysql+mysqlconnector://ryan:Tes09P!!@localhost/flutter-pos-db"